MODEL:
  patch_height: 7
  patch_width: 7
  num_channels: 1
  d: 64
  d_mlp: 128
  num_heads: 3
  pool_size: 8
  d_out: 10
DEVICE: "cuda"
DATA:
  DATASET: "mnist"
  TRAIN_DATALOADER:
    batch_size: 256
  TEST_DATALOADER:
    batch_size: 128
OPTIMIZER:
  type: "adam"
  lr: 0.00005
  weight_decay: 0.0
SCHEDULER:
  # type: null # "CosineAnnealingWarmRestarts"
  T_0: 150
TRAINING_LOOP:
  n_epochs: 20
  validation_frequency: 100
LOSS_WEIGHTS:
  l1_loss: 1.0
  regularization: 0.0005