OUTPUT_DIR: "efir/results"
DEVICE: "cuda"
DATA:
  DATASET: "mnist"
  TRAIN_DATALOADER:
    batch_size: 128
  TEST_DATALOADER:
    batch_size: 128
MODEL:
  type: "vae"
  encoded_space_dim: 256
  fc2_input_dim: 256
OPTIMIZER:
  type: "adam"
  lr: 0.001
  weight_decay: 0.0
enable_scheduler: True
SCHEDULER:
  type: "CosineAnnealingWarmRestarts"
  T_0: 150
TRAINING_LOOP:
  n_epochs: 20
  validation_frequency: 100
LOSS_WEIGHTS:
  mse_loss: 1.0
  regularization: 0.001